using System;
using System.Collections.Generic;
using System.Linq;

namespace AdventOfCode2020 {
    public class Day7 : Day {

        private const string goalBag = "shiny gold";

        private static readonly Dictionary<string, Bag> allBags = new Dictionary<string, Bag>();
        
        public void Run() {
            foreach (var bag in data) {
                allBags.Add(bag.bag, bag);
            }

            var partOne = data.Count(bag => bag.HasGoalBag);
            var partTwo = allBags["shiny gold"].Value;
            
            Console.WriteLine($"Day 7: {partTwo} bags");
        }

        private class Bag {

            private bool? _cachedHasGoalBag;

            public bool HasGoalBag {
                get {
                    if (_cachedHasGoalBag.HasValue) return _cachedHasGoalBag.Value;

                    foreach (var content in contents) {
                        if (content.b.Equals(goalBag)) {
                            _cachedHasGoalBag = true;
                            return true;
                        }
                        
                        if (allBags.TryGetValue(content.b, out var bag)) {
                            if (bag.HasGoalBag) {
                                _cachedHasGoalBag = true;
                                return true;
                            }
                        } else {
                            Console.WriteLine($"Couldn't get rule for {content.b} bags");
                        }
                    }

                    _cachedHasGoalBag = false;
                    return false;
                }
            }

            private int _value;

            public int Value {
                get {
                    if (_value != 0) return _value;

                    _value = 1;
                    foreach (var content in contents) {
                        _value += content.count * allBags[content.b].Value;
                    }

                    Console.WriteLine($"{bag}: {_value}");
                    return _value;
                }
            }

            public string bag;
            public (int count, string b)[] contents;
            
            public Bag(string bag, params (int count, string b)[] contents) {
                this.bag = bag;
                this.contents = contents;
            }
        }

        private Bag[] data = {
            new Bag("mirrored beige", (1, "drab brown"), (3, "dotted crimson")),
new Bag("light lavender", (5, "clear teal"), (2, "wavy gold"), (5, "drab maroon"), (2, "posh cyan")),
new Bag("drab gold", (2, "posh aqua"), (3, "dark olive")),
new Bag("plaid lime", (5, "posh purple")),
new Bag("pale brown", (2, "dotted teal"), (4, "light plum")),
new Bag("vibrant orange", (3, "dim cyan"), (1, "shiny gold"), (1, "shiny salmon")),
new Bag("dull olive", (5, "wavy yellow"), (5, "striped crimson"), (2, "dotted maroon")),
new Bag("dull violet", (1, "posh orange"), (2, "muted plum"), (2, "mirrored bronze"), (2, "dull chartreuse")),
new Bag("shiny maroon", (5, "wavy gold"), (2, "striped coral"), (1, "muted silver")),
new Bag("clear red", (5, "plaid lavender")),
new Bag("dull blue", (3, "plaid crimson")),
new Bag("faded black", (5, "dull orange")),
new Bag("clear aqua", (4, "dull white"), (4, "dotted cyan")),
new Bag("pale tomato", (3, "bright beige")),
new Bag("drab yellow", (1, "muted aqua"), (5, "dull purple"), (5, "light chartreuse")),
new Bag("muted yellow", (1, "vibrant lavender"), (3, "vibrant cyan"), (2, "faded gray")),
new Bag("bright lime", (3, "dull gray"), (2, "vibrant bronze"), (4, "light purple"), (1, "wavy gray")),
new Bag("vibrant bronze", (5, "plaid blue"), (2, "plaid beige")),
new Bag("posh teal", (3, "wavy magenta"), (4, "muted bronze")),
new Bag("muted indigo", (3, "dark black"), (3, "mirrored orange"), (2, "clear crimson")),
new Bag("dull beige", (4, "dim tan"), (2, "posh blue"), (1, "dull silver"), (2, "bright chartreuse")),
new Bag("posh magenta", (4, "light brown")),
new Bag("vibrant olive", (2, "vibrant purple"), (3, "dull gold"), (1, "clear olive"), (3, "clear plum")),
new Bag("bright beige", (5, "faded teal"), (3, "light bronze"), (5, "vibrant yellow")),
new Bag("posh gray", (2, "clear magenta"), (2, "wavy white"), (2, "mirrored olive"), (2, "vibrant violet")),
new Bag("dim gray", (5, "plaid gold"), (4, "bright teal"), (5, "light indigo"), (4, "wavy salmon")),
new Bag("clear indigo", (3, "striped salmon"), (5, "plaid maroon"), (3, "pale beige"), (4, "pale chartreuse")),
new Bag("dark coral", (1, "dotted olive"), (4, "faded salmon")),
new Bag("faded green", (3, "muted purple"), (3, "striped salmon"), (1, "mirrored aqua"), (1, "faded bronze")),
new Bag("muted blue", (5, "drab white"), (5, "muted tomato"), (1, "dark brown")),
new Bag("dark lime", (3, "striped blue"), (5, "dark silver"), (4, "bright red"), (1, "plaid crimson")),
new Bag("muted orange", (3, "dark violet"), (2, "shiny tan")),
new Bag("muted lavender", (2, "vibrant lime"), (5, "dotted white"), (3, "posh plum"), (5, "plaid blue")),
new Bag("light olive", (4, "posh tomato"), (2, "pale chartreuse"), (3, "mirrored teal")),
new Bag("shiny crimson", (4, "dim red"), (1, "vibrant crimson"), (5, "dim cyan"), (3, "faded silver")),
new Bag("wavy salmon", (2, "muted olive")),
new Bag("light red", (5, "wavy tomato"), (3, "clear fuchsia"), (2, "wavy blue"), (2, "vibrant fuchsia")),
new Bag("vibrant violet", (5, "wavy red")),
new Bag("vibrant green", (2, "wavy maroon"), (5, "wavy black"), (1, "dark bronze"), (1, "light cyan")),
new Bag("dull black", (3, "mirrored white"), (1, "dim lavender"), (1, "faded blue")),
new Bag("shiny yellow", (1, "dotted plum")),
new Bag("striped white", (2, "pale salmon"), (2, "shiny white"), (2, "dark gray"), (2, "pale orange")),
new Bag("posh yellow", (4, "dotted tan"), (3, "clear coral"), (5, "wavy magenta"), (4, "striped white")),
new Bag("dark red", (1, "dotted olive"), (2, "posh orange"), (3, "striped gold")),
new Bag("wavy black", (1, "bright cyan"), (4, "muted orange")),
new Bag("dull white", (4, "pale red"), (1, "light lavender")),
new Bag("mirrored tomato", (1, "dark green"), (4, "light yellow"), (1, "muted tan")),
new Bag("dim gold", (3, "vibrant white")),
new Bag("dim plum", (4, "light red")),
new Bag("pale lime", (1, "pale maroon"), (2, "bright magenta"), (5, "mirrored purple")),
new Bag("light magenta", (2, "bright maroon")),
new Bag("wavy gray", (5, "shiny violet"), (3, "plaid bronze"), (2, "pale salmon"), (2, "mirrored maroon")),
new Bag("light brown", (5, "muted tomato"), (1, "dull green"), (2, "wavy turquoise")),
new Bag("clear teal", (2, "muted olive"), (1, "dull purple"), (2, "bright magenta")),
new Bag("plaid maroon", (5, "light plum"), (2, "muted aqua"), (2, "light chartreuse"), (1, "dim tomato")),
new Bag("dotted salmon", (5, "dark brown"), (2, "mirrored gold")),
new Bag("light orange", (4, "muted aqua"), (3, "light plum")),
new Bag("vibrant blue", (1, "wavy yellow")),
new Bag("dark white", (3, "shiny magenta")),
new Bag("muted red", (2, "faded violet")),
new Bag("vibrant crimson", (5, "striped gold"), (5, "striped white"), (4, "bright lavender")),
new Bag("dim brown", (5, "dotted olive"), (2, "striped white"), (3, "shiny black"), (5, "striped beige")),
new Bag("wavy indigo", (1, "dim brown"), (2, "plaid yellow"), (1, "faded yellow")),
new Bag("dim coral", (5, "light orange"), (3, "bright red"), (1, "wavy turquoise"), (2, "pale maroon")),
new Bag("mirrored salmon", (1, "drab blue"), (3, "muted bronze"), (1, "muted brown")),
new Bag("striped olive", (1, "dim bronze")),
new Bag("bright tan", (5, "dark brown")),
new Bag("drab violet", (5, "mirrored plum"), (2, "mirrored purple")),
new Bag("dark purple", (3, "striped yellow"), (1, "pale orange"), (4, "dull fuchsia"), (5, "faded silver")),
new Bag("striped tan", (3, "shiny salmon"), (5, "striped brown"), (1, "light gray")),
new Bag("posh aqua", (1, "striped crimson")),
new Bag("mirrored black", (2, "pale crimson"), (3, "posh lavender")),
new Bag("faded indigo", (5, "dotted purple"), (5, "bright green")),
new Bag("dim aqua", (3, "muted coral"), (3, "shiny fuchsia"), (2, "light indigo"), (5, "muted cyan")),
new Bag("dim bronze", (2, "faded tomato"), (4, "faded tan"), (5, "dull teal")),
new Bag("dotted green", (1, "vibrant gray"), (4, "wavy silver"), (2, "posh lavender"), (3, "wavy magenta")),
new Bag("faded gold", (5, "pale salmon"), (2, "wavy silver"), (2, "bright olive"), (2, "plaid blue")),
new Bag("muted plum", (1, "light fuchsia"), (2, "posh silver"), (5, "mirrored lime"), (5, "faded silver")),
new Bag("striped green", (1, "plaid gray")),
new Bag("posh turquoise", (4, "drab maroon")),
new Bag("dim violet"),
new Bag("striped violet", (5, "pale aqua"), (2, "wavy coral")),
new Bag("dotted yellow", (2, "faded lime"), (4, "dull turquoise")),
new Bag("muted aqua"),
new Bag("wavy maroon", (2, "dim fuchsia"), (4, "mirrored teal"), (1, "muted brown"), (2, "muted gray")),
new Bag("clear maroon", (4, "dotted maroon"), (4, "pale blue")),
new Bag("dim red", (1, "pale lime"), (4, "dim cyan")),
new Bag("dark maroon", (4, "dark silver"), (2, "pale indigo")),
new Bag("faded red", (1, "faded black"), (4, "bright orange"), (1, "posh gray"), (1, "striped crimson")),
new Bag("dark turquoise", (3, "vibrant tan"), (4, "pale brown")),
new Bag("pale gray", (3, "dark gray"), (1, "wavy red"), (1, "dark plum")),
new Bag("shiny teal", (5, "light yellow"), (3, "striped beige"), (5, "plaid red"), (2, "faded maroon")),
new Bag("posh indigo", (3, "posh cyan"), (2, "bright lavender")),
new Bag("striped chartreuse", (4, "dim maroon"), (1, "pale coral"), (2, "bright plum"), (3, "clear black")),
new Bag("faded violet", (5, "dark purple"), (2, "plaid tan"), (4, "faded yellow"), (1, "faded salmon")),
new Bag("clear gray", (3, "light lavender")),
new Bag("muted brown", (3, "pale orange"), (2, "bright lavender"), (3, "clear red"), (1, "dark tan")),
new Bag("dotted gold", (2, "plaid aqua"), (3, "pale fuchsia"), (4, "mirrored blue"), (2, "dull maroon")),
new Bag("dark yellow", (3, "dotted maroon"), (2, "wavy coral")),
new Bag("dull tan", (2, "plaid indigo"), (3, "dotted gray")),
new Bag("muted salmon", (4, "dim lime")),
new Bag("clear turquoise", (3, "mirrored green")),
new Bag("dark chartreuse", (2, "vibrant coral")),
new Bag("plaid green", (5, "pale indigo"), (2, "faded blue"), (2, "bright lavender"), (1, "drab indigo")),
new Bag("dim black", (5, "light tomato")),
new Bag("posh blue", (1, "dull lime"), (1, "posh maroon"), (5, "dim tomato")),
new Bag("bright violet", (3, "dim black"), (4, "faded red"), (5, "bright salmon"), (3, "vibrant tomato")),
new Bag("faded plum", (4, "clear teal"), (1, "faded lavender"), (3, "wavy crimson"), (4, "drab salmon")),
new Bag("bright fuchsia", (2, "vibrant teal")),
new Bag("posh olive", (3, "dotted gray")),
new Bag("muted black", (2, "dotted coral"), (5, "dotted lime"), (5, "pale teal"), (4, "light plum")),
new Bag("mirrored coral", (4, "drab yellow"), (2, "muted olive"), (2, "dotted teal")),
new Bag("muted lime", (1, "clear white"), (1, "striped yellow"), (1, "vibrant silver"), (4, "striped violet")),
new Bag("dark teal", (3, "light plum"), (5, "posh salmon"), (2, "posh white")),
new Bag("muted magenta", (5, "faded gray"), (1, "clear red"), (3, "muted maroon")),
new Bag("bright indigo", (4, "pale chartreuse"), (3, "faded blue")),
new Bag("striped crimson", (3, "dotted red"), (5, "dark tan"), (2, "plaid lime")),
new Bag("clear yellow", (5, "dark bronze"), (1, "mirrored olive")),
new Bag("dark olive", (5, "striped gold"), (1, "faded bronze"), (5, "wavy blue"), (3, "bright lavender")),
new Bag("clear black", (5, "vibrant white"), (3, "wavy white"), (1, "mirrored black")),
new Bag("wavy tan", (5, "vibrant gray"), (2, "shiny salmon"), (5, "posh purple"), (5, "shiny white")),
new Bag("light tomato", (5, "striped blue"), (3, "posh cyan")),
new Bag("dull chartreuse", (4, "dim white"), (5, "faded violet"), (1, "mirrored coral")),
new Bag("mirrored gold", (1, "drab white")),
new Bag("striped gray", (3, "mirrored teal")),
new Bag("striped fuchsia", (2, "dotted lime"), (5, "clear olive"), (3, "dotted yellow")),
new Bag("muted gold", (1, "dark olive"), (3, "posh plum"), (5, "muted magenta"), (1, "light lavender")),
new Bag("striped silver", (1, "dark brown"), (2, "drab salmon")),
new Bag("plaid bronze", (3, "light plum"), (4, "plaid lime"), (2, "faded orange"), (1, "mirrored coral")),
new Bag("pale tan", (5, "posh gray"), (4, "dotted violet"), (5, "posh fuchsia"), (5, "light silver")),
new Bag("dotted tomato", (3, "vibrant white"), (2, "posh yellow")),
new Bag("pale maroon", (4, "dotted teal"), (5, "bright olive"), (4, "striped gold"), (4, "bright lavender")),
new Bag("pale coral", (5, "dull cyan"), (1, "muted aqua"), (1, "dull lime"), (1, "pale orange")),
new Bag("drab blue", (4, "shiny olive"), (5, "faded maroon")),
new Bag("dull turquoise", (2, "muted olive"), (4, "pale green")),
new Bag("dotted violet", (3, "plaid tan"), (5, "wavy turquoise"), (1, "plaid maroon")),
new Bag("shiny chartreuse", (1, "mirrored silver")),
new Bag("clear crimson", (5, "bright plum"), (2, "muted silver")),
new Bag("faded tan", (4, "pale indigo"), (3, "wavy red"), (5, "light gold")),
new Bag("light black", (4, "dark aqua")),
new Bag("plaid yellow", (2, "pale silver"), (1, "wavy blue"), (4, "bright lavender")),
new Bag("faded silver", (5, "clear tan")),
new Bag("light yellow", (1, "pale beige")),
new Bag("drab bronze", (4, "pale maroon"), (5, "faded tomato"), (1, "vibrant crimson"), (4, "dull indigo")),
new Bag("dark plum", (2, "dark gray"), (1, "pale chartreuse")),
new Bag("muted green", (1, "dull gray"), (1, "light purple")),
new Bag("clear white", (5, "dotted plum"), (2, "light orange")),
new Bag("faded chartreuse", (1, "dim crimson"), (1, "light gray")),
new Bag("mirrored aqua", (2, "dim teal"), (4, "muted silver"), (1, "striped salmon")),
new Bag("light bronze", (5, "pale purple"), (1, "faded teal")),
new Bag("mirrored indigo", (1, "wavy red"), (5, "faded tomato")),
new Bag("plaid chartreuse", (5, "bright cyan")),
new Bag("light fuchsia", (5, "faded violet")),
new Bag("mirrored orange", (1, "drab lavender")),
new Bag("light indigo", (5, "wavy plum"), (5, "vibrant chartreuse")),
new Bag("posh black", (1, "dull brown")),
new Bag("mirrored yellow", (2, "shiny gray")),
new Bag("bright white", (2, "shiny silver"), (1, "dotted lime")),
new Bag("dark brown", (5, "bright magenta"), (1, "striped beige"), (5, "pale beige")),
new Bag("faded lavender", (3, "faded gold"), (3, "vibrant crimson"), (2, "pale aqua")),
new Bag("dotted cyan", (5, "drab salmon"), (5, "clear blue"), (3, "wavy blue"), (3, "posh cyan")),
new Bag("clear coral", (2, "light indigo")),
new Bag("plaid tan", (3, "vibrant teal"), (4, "mirrored gold")),
new Bag("striped magenta", (4, "posh magenta"), (4, "dim chartreuse"), (1, "muted lime"), (4, "vibrant aqua")),
new Bag("pale red", (5, "dull plum"), (3, "wavy blue"), (4, "pale beige")),
new Bag("posh cyan", (5, "shiny white"), (4, "muted coral"), (2, "pale chartreuse"), (2, "dark gray")),
new Bag("posh tan", (1, "plaid tan"), (5, "dim tan")),
new Bag("dotted coral", (5, "pale plum"), (1, "dull olive"), (4, "light gray"), (3, "pale yellow")),
new Bag("shiny silver", (3, "dull teal"), (2, "dotted teal"), (2, "bright magenta")),
new Bag("drab white", (5, "dark violet")),
new Bag("plaid teal", (2, "pale green"), (4, "dim cyan"), (1, "drab white"), (3, "dull salmon")),
new Bag("faded magenta", (1, "posh blue"), (4, "clear coral")),
new Bag("muted fuchsia", (1, "faded aqua"), (4, "mirrored magenta"), (2, "wavy purple")),
new Bag("dark lavender", (5, "dull fuchsia"), (1, "dull salmon"), (3, "plaid blue")),
new Bag("bright magenta", (3, "shiny white"), (4, "pale chartreuse"), (3, "drab yellow"), (1, "dull purple")),
new Bag("vibrant lime", (4, "striped coral"), (3, "shiny salmon"), (3, "light lime"), (5, "dark tan")),
new Bag("vibrant beige", (2, "mirrored turquoise"), (4, "dim orange"), (4, "muted green")),
new Bag("drab brown", (4, "plaid gray")),
new Bag("dotted plum", (4, "dark plum"), (3, "pale brown")),
new Bag("vibrant turquoise", (4, "dark purple")),
new Bag("dark silver", (3, "faded blue"), (4, "dim aqua"), (5, "plaid turquoise"), (1, "bright cyan")),
new Bag("posh silver", (4, "faded tomato"), (2, "muted olive")),
new Bag("drab beige", (1, "pale beige")),
new Bag("mirrored brown", (2, "posh olive"), (4, "vibrant teal"), (5, "pale red")),
new Bag("plaid black", (1, "clear teal"), (3, "shiny crimson")),
new Bag("shiny violet", (3, "mirrored white")),
new Bag("wavy fuchsia", (3, "wavy gold")),
new Bag("bright gold", (1, "dark violet"), (5, "dark beige"), (2, "bright salmon")),
new Bag("light gold", (5, "bright magenta"), (3, "dim violet"), (1, "light lavender"), (2, "shiny white")),
new Bag("dark orange", (5, "muted olive")),
new Bag("dull gold", (1, "light tomato"), (4, "striped lavender"), (2, "shiny tomato"), (2, "plaid lime")),
new Bag("mirrored crimson", (4, "plaid crimson"), (4, "shiny cyan"), (2, "bright cyan")),
new Bag("dim tan", (3, "striped tan"), (5, "plaid crimson")),
new Bag("shiny turquoise", (5, "light chartreuse"), (2, "pale chartreuse"), (4, "dotted teal")),
new Bag("wavy beige", (5, "pale aqua"), (2, "pale brown")),
new Bag("shiny orange", (1, "dotted gray"), (1, "plaid chartreuse"), (2, "wavy purple"), (2, "dim white")),
new Bag("dark black", (3, "dim violet"), (4, "striped brown")),
new Bag("dotted purple", (4, "drab red"), (3, "posh cyan"), (3, "dotted green"), (3, "dark green")),
new Bag("bright yellow", (4, "muted coral")),
new Bag("pale teal", (1, "vibrant yellow"), (4, "faded lavender")),
new Bag("light purple", (4, "drab yellow"), (5, "plaid red"), (5, "wavy white"), (3, "bright olive")),
new Bag("mirrored lavender", (5, "dotted beige"), (2, "dark coral")),
new Bag("wavy chartreuse"),
new Bag("pale purple", (2, "posh plum"), (3, "dim silver"), (5, "vibrant chartreuse"), (4, "pale salmon")),
new Bag("dotted gray", (5, "muted tomato")),
new Bag("vibrant maroon", (3, "light red")),
new Bag("plaid purple", (5, "bright magenta"), (2, "vibrant cyan"), (4, "drab maroon")),
new Bag("dim maroon", (3, "dotted teal"), (2, "striped silver"), (4, "dim white"), (4, "pale purple")),
new Bag("posh lavender", (5, "light magenta"), (1, "dim lime"), (1, "vibrant red"), (1, "light purple")),
new Bag("wavy tomato", (1, "shiny tan"), (4, "plaid blue")),
new Bag("muted turquoise", (3, "drab olive"), (2, "dotted beige"), (2, "wavy turquoise"), (3, "faded yellow")),
new Bag("shiny bronze", (5, "dim black")),
new Bag("dim white", (5, "dim purple"), (4, "pale red"), (5, "plaid lime"), (5, "striped silver")),
new Bag("faded maroon", (2, "dark tan"), (4, "dotted olive"), (2, "striped gold")),
new Bag("muted silver", (1, "plaid red")),
new Bag("dark salmon", (2, "drab maroon"), (5, "posh green")),
new Bag("pale chartreuse", (5, "dim violet"), (4, "muted aqua")),
new Bag("bright chartreuse", (5, "shiny cyan")),
new Bag("plaid gold", (5, "shiny chartreuse"), (2, "clear red"), (1, "bright yellow"), (5, "mirrored lime")),
new Bag("light lime", (4, "dotted red")),
new Bag("bright tomato", (2, "wavy orange")),
new Bag("wavy white", (3, "striped white"), (3, "pale beige"), (1, "light plum")),
new Bag("mirrored gray", (1, "dull gray"), (4, "plaid beige"), (3, "wavy turquoise"), (1, "pale maroon")),
new Bag("shiny purple", (2, "muted maroon")),
new Bag("mirrored lime", (2, "mirrored fuchsia"), (5, "dark lavender"), (4, "dull lime")),
new Bag("dotted tan", (2, "pale maroon")),
new Bag("mirrored olive", (2, "drab beige"), (4, "plaid crimson"), (4, "bright turquoise"), (3, "clear gold")),
new Bag("shiny salmon", (1, "faded tomato"), (3, "drab white"), (1, "faded crimson")),
new Bag("shiny olive", (3, "bright olive"), (4, "light orange"), (1, "pale maroon"), (3, "posh purple")),
new Bag("wavy aqua", (3, "light brown"), (3, "dotted salmon"), (3, "vibrant brown"), (1, "dark beige")),
new Bag("bright bronze", (1, "clear white"), (3, "clear cyan"), (1, "shiny black"), (5, "bright red")),
new Bag("dim lime", (5, "drab lavender"), (2, "vibrant aqua")),
new Bag("dull cyan", (3, "mirrored coral")),
new Bag("dark crimson", (5, "faded yellow"), (5, "faded maroon"), (3, "faded magenta")),
new Bag("plaid silver", (2, "dull maroon"), (3, "drab cyan")),
new Bag("plaid aqua", (1, "wavy silver"), (2, "plaid orange")),
new Bag("bright black", (1, "posh silver")),
new Bag("vibrant silver", (4, "clear chartreuse"), (2, "pale brown"), (4, "pale orange"), (2, "light lavender")),
new Bag("wavy purple", (5, "shiny tan"), (4, "dim brown"), (4, "faded crimson")),
new Bag("posh beige", (5, "plaid olive"), (2, "dotted turquoise")),
new Bag("striped orange", (5, "dark chartreuse"), (3, "wavy fuchsia"), (4, "wavy coral"), (2, "plaid indigo")),
new Bag("clear bronze", (1, "faded orange"), (5, "shiny teal")),
new Bag("dull tomato", (5, "muted gray"), (5, "muted brown"), (4, "dull teal"), (2, "plaid maroon")),
new Bag("plaid cyan", (5, "dull plum"), (1, "clear red"), (1, "shiny salmon")),
new Bag("mirrored teal", (2, "dim purple"), (4, "muted coral")),
new Bag("vibrant aqua", (1, "clear gold"), (1, "dark red"), (5, "dull purple")),
new Bag("dull magenta", (2, "dull lavender")),
new Bag("light maroon", (3, "clear plum"), (2, "plaid olive"), (5, "dull blue")),
new Bag("wavy blue", (1, "pale orange"), (1, "pale brown"), (2, "striped salmon")),
new Bag("bright crimson", (5, "clear gold")),
new Bag("striped aqua", (2, "bright brown"), (5, "faded tan"), (3, "wavy chartreuse")),
new Bag("muted gray", (1, "dotted red")),
new Bag("posh coral", (5, "vibrant gray"), (3, "faded teal"), (3, "dim lavender")),
new Bag("bright plum", (5, "mirrored aqua"), (4, "shiny tan"), (3, "dim tomato")),
new Bag("shiny white"),
new Bag("plaid crimson", (3, "faded gray"), (3, "wavy white"), (1, "faded lavender"), (1, "mirrored gold")),
new Bag("dull indigo", (3, "shiny olive")),
new Bag("mirrored silver", (4, "drab blue"), (1, "mirrored maroon"), (2, "plaid maroon")),
new Bag("dotted white", (3, "dotted fuchsia"), (5, "vibrant aqua"), (1, "muted tan")),
new Bag("posh white", (3, "light lavender"), (1, "wavy white"), (4, "dotted teal")),
new Bag("dim salmon", (5, "muted magenta")),
new Bag("shiny blue", (5, "light chartreuse"), (1, "shiny fuchsia"), (4, "muted bronze")),
new Bag("faded turquoise", (2, "light silver"), (4, "dull salmon"), (4, "dim teal")),
new Bag("dim indigo", (1, "dark bronze"), (5, "muted brown"), (2, "pale magenta")),
new Bag("bright salmon", (3, "vibrant white"), (2, "dark tan")),
new Bag("clear violet", (3, "shiny coral"), (2, "wavy purple")),
new Bag("posh crimson", (5, "posh silver"), (5, "posh plum"), (2, "dull crimson"), (3, "posh blue")),
new Bag("faded salmon", (2, "posh white"), (5, "mirrored fuchsia"), (2, "wavy fuchsia"), (1, "dotted tan")),
new Bag("bright cyan", (5, "striped beige")),
new Bag("light gray", (5, "dotted red"), (1, "faded gray"), (3, "bright olive")),
new Bag("mirrored green", (3, "dotted lime"), (2, "dull salmon"), (2, "dim indigo")),
new Bag("dark tan", (2, "pale green")),
new Bag("light tan", (4, "dark coral"), (3, "clear indigo")),
new Bag("pale blue", (5, "dull brown"), (1, "posh white")),
new Bag("clear chartreuse", (5, "dim tomato"), (2, "vibrant crimson"), (5, "pale green"), (4, "shiny white")),
new Bag("wavy lavender", (5, "posh gray"), (2, "dark olive"), (4, "drab yellow"), (4, "light blue")),
new Bag("faded olive", (1, "bright yellow")),
new Bag("pale silver", (1, "pale beige"), (4, "striped white")),
new Bag("clear cyan", (1, "light green"), (5, "striped lavender"), (4, "muted bronze"), (5, "light yellow")),
new Bag("mirrored white", (3, "shiny green"), (2, "bright silver"), (2, "posh black")),
new Bag("dark bronze", (3, "dotted red")),
new Bag("faded gray", (5, "faded crimson")),
new Bag("dull purple"),
new Bag("striped cyan", (4, "dull purple"), (1, "shiny fuchsia"), (3, "striped green"), (2, "muted teal")),
new Bag("posh brown", (2, "shiny gray"), (1, "dull teal")),
new Bag("bright blue", (4, "wavy gold"), (4, "muted beige"), (1, "posh salmon"), (1, "vibrant yellow")),
new Bag("mirrored violet", (5, "light plum"), (4, "plaid yellow"), (2, "dim brown"), (5, "clear tan")),
new Bag("wavy bronze", (2, "drab blue")),
new Bag("muted purple", (4, "muted olive")),
new Bag("dotted olive", (2, "dull orange"), (3, "wavy gold"), (3, "bright olive"), (5, "pale green")),
new Bag("dark gray"),
new Bag("dim beige", (1, "mirrored olive"), (5, "dim cyan")),
new Bag("drab green", (3, "wavy gold"), (2, "clear gold"), (4, "dull cyan"), (1, "pale yellow")),
new Bag("clear lavender", (1, "dull crimson"), (4, "pale red")),
new Bag("drab black", (3, "bright white"), (3, "dim white"), (4, "light teal")),
new Bag("plaid coral", (3, "light plum"), (4, "wavy aqua")),
new Bag("pale white", (5, "light gray"), (2, "light indigo"), (4, "shiny blue")),
new Bag("drab lime", (3, "dull lime"), (2, "dotted gray")),
new Bag("shiny green", (3, "striped gold"), (3, "faded crimson")),
new Bag("light beige", (3, "mirrored maroon"), (1, "bright magenta"), (1, "vibrant coral"), (4, "dull fuchsia")),
new Bag("striped lime", (5, "dim magenta"), (2, "muted orange"), (4, "dull aqua")),
new Bag("shiny tomato", (1, "dim blue")),
new Bag("pale gold", (1, "clear indigo"), (5, "posh gold")),
new Bag("striped beige", (3, "dark plum"), (2, "pale salmon"), (1, "striped white"), (5, "dull purple")),
new Bag("dull brown", (5, "pale yellow"), (4, "pale silver"), (4, "pale red")),
new Bag("pale aqua", (4, "posh silver")),
new Bag("shiny gold", (5, "pale green"), (5, "faded gold")),
new Bag("muted tan", (2, "vibrant red"), (3, "faded crimson")),
new Bag("striped red", (1, "striped tan"), (4, "dim purple"), (2, "posh lime")),
new Bag("wavy red", (3, "clear indigo")),
new Bag("light aqua", (3, "light coral"), (3, "drab salmon"), (1, "bright lavender"), (1, "drab turquoise")),
new Bag("shiny brown", (3, "bright indigo"), (3, "plaid beige")),
new Bag("striped maroon", (3, "dim silver"), (3, "mirrored silver")),
new Bag("dim crimson", (3, "wavy yellow"), (2, "pale lime"), (5, "dull magenta")),
new Bag("clear salmon", (4, "dull fuchsia"), (1, "dull maroon"), (5, "light green")),
new Bag("dark green", (5, "striped beige"), (4, "shiny gray"), (1, "shiny black")),
new Bag("vibrant red", (4, "drab blue"), (3, "light plum"), (1, "posh orange"), (4, "dull silver")),
new Bag("dotted blue", (5, "dull coral")),
new Bag("vibrant purple", (5, "dull tan"), (2, "faded chartreuse"), (4, "light aqua")),
new Bag("striped yellow", (3, "faded gold"), (4, "wavy gold"), (2, "pale brown"), (1, "light yellow")),
new Bag("pale magenta", (2, "faded crimson"), (3, "striped violet"), (3, "vibrant chartreuse"), (3, "wavy red")),
new Bag("dull fuchsia", (1, "pale brown"), (5, "dim purple"), (2, "pale gray")),
new Bag("wavy brown", (4, "clear brown"), (4, "faded aqua"), (4, "muted tomato")),
new Bag("vibrant yellow", (3, "dark tan"), (3, "light lavender")),
new Bag("light crimson", (5, "shiny gray"), (3, "dim green"), (3, "dark black")),
new Bag("vibrant chartreuse", (4, "plaid blue"), (5, "pale beige")),
new Bag("faded yellow", (5, "wavy gold"), (3, "plaid bronze"), (5, "plaid red")),
new Bag("drab orange", (1, "pale gray"), (3, "drab lavender"), (3, "dull lime"), (1, "wavy olive")),
new Bag("light chartreuse"),
new Bag("shiny cyan", (2, "striped beige"), (4, "mirrored maroon"), (4, "dark yellow"), (4, "bright indigo")),
new Bag("dull aqua", (5, "bright white"), (3, "dull coral"), (1, "faded yellow"), (4, "dull gray")),
new Bag("muted teal", (2, "bright silver"), (3, "faded orange")),
new Bag("pale bronze", (5, "posh teal"), (3, "drab indigo"), (3, "dim tomato")),
new Bag("vibrant salmon", (2, "dull salmon")),
new Bag("plaid blue", (2, "pale salmon"), (2, "dark gray")),
new Bag("faded beige", (1, "vibrant plum"), (4, "light lime"), (1, "posh indigo"), (4, "posh brown")),
new Bag("bright aqua", (2, "dotted plum"), (1, "dotted violet"), (5, "light orange"), (1, "muted chartreuse")),
new Bag("muted chartreuse", (3, "plaid lavender"), (1, "wavy beige")),
new Bag("dark violet", (2, "wavy crimson")),
new Bag("dull yellow", (2, "plaid red"), (2, "striped brown"), (1, "wavy plum")),
new Bag("bright olive", (3, "dark gray")),
new Bag("bright green", (4, "muted aqua"), (2, "wavy tomato")),
new Bag("clear magenta", (5, "plaid maroon"), (2, "vibrant teal"), (3, "clear indigo")),
new Bag("pale plum", (1, "pale purple"), (4, "vibrant fuchsia")),
new Bag("plaid beige", (2, "posh tomato"), (3, "mirrored maroon"), (5, "light purple")),
new Bag("plaid tomato", (4, "dull gray")),
new Bag("posh fuchsia", (4, "mirrored indigo"), (4, "faded salmon"), (1, "striped orange"), (3, "striped yellow")),
new Bag("dull salmon", (1, "vibrant crimson"), (4, "muted olive"), (3, "dark brown")),
new Bag("striped brown", (1, "dull coral"), (3, "shiny silver"), (4, "posh white")),
new Bag("drab plum", (5, "wavy olive"), (5, "shiny tomato"), (3, "bright green")),
new Bag("vibrant tan", (4, "pale beige")),
new Bag("bright turquoise", (4, "vibrant teal"), (3, "dotted teal"), (2, "dark violet"), (4, "bright magenta")),
new Bag("wavy lime", (5, "wavy green"), (1, "muted gold"), (1, "dim purple")),
new Bag("striped gold", (3, "posh cyan"), (3, "muted coral"), (3, "wavy silver")),
new Bag("dull orange", (2, "striped beige"), (2, "posh cyan"), (2, "shiny gold")),
new Bag("dotted lavender", (5, "vibrant aqua"), (4, "bright turquoise"), (2, "drab turquoise"), (3, "dim aqua")),
new Bag("mirrored blue", (5, "bright teal")),
new Bag("bright coral", (3, "plaid salmon"), (4, "pale gray")),
new Bag("dark fuchsia", (2, "vibrant aqua"), (2, "bright salmon")),
new Bag("pale fuchsia", (5, "drab blue"), (1, "striped plum"), (3, "muted teal")),
new Bag("dotted indigo", (5, "striped lavender"), (2, "bright cyan"), (2, "light gray"), (3, "plaid beige")),
new Bag("posh tomato", (3, "dim red"), (4, "clear coral"), (5, "mirrored olive"), (2, "dull cyan")),
new Bag("dull silver", (2, "plaid red"), (2, "faded silver"), (5, "mirrored maroon")),
new Bag("mirrored fuchsia", (2, "bright magenta"), (1, "dark gray")),
new Bag("muted cyan", (2, "mirrored teal"), (3, "dull fuchsia"), (5, "dotted olive")),
new Bag("shiny black", (2, "shiny white")),
new Bag("dull crimson", (2, "dim tomato"), (1, "clear chartreuse"), (3, "dull teal")),
new Bag("mirrored turquoise", (3, "dull maroon"), (1, "shiny aqua"), (2, "mirrored violet")),
new Bag("plaid olive", (3, "striped brown"), (5, "muted olive"), (4, "faded tomato"), (1, "vibrant teal")),
new Bag("posh lime", (3, "plaid indigo"), (2, "light yellow"), (2, "pale blue"), (4, "bright maroon")),
new Bag("plaid plum", (3, "muted orange"), (1, "dim tan")),
new Bag("dotted magenta", (1, "mirrored teal"), (3, "light lime"), (5, "shiny tan"), (2, "vibrant coral")),
new Bag("dark gold", (2, "muted orange"), (4, "mirrored yellow")),
new Bag("pale green", (5, "striped white"), (1, "mirrored coral"), (3, "dark plum"), (5, "clear teal")),
new Bag("drab red", (1, "vibrant coral"), (4, "drab lavender"), (5, "posh orange"), (3, "striped white")),
new Bag("posh green", (1, "faded yellow"), (3, "light blue")),
new Bag("shiny lime", (1, "pale beige"), (1, "dark silver")),
new Bag("plaid magenta", (2, "light beige"), (5, "muted plum"), (1, "shiny coral")),
new Bag("posh salmon", (2, "vibrant brown"), (5, "pale teal"), (4, "bright cyan"), (4, "shiny lime")),
new Bag("dotted orange", (4, "plaid cyan"), (5, "light magenta"), (3, "dull chartreuse"), (5, "faded orange")),
new Bag("dull lavender", (3, "vibrant gray"), (5, "vibrant magenta"), (2, "dim brown"), (5, "mirrored silver")),
new Bag("shiny indigo", (4, "posh purple"), (4, "muted tomato")),
new Bag("light silver", (2, "striped crimson"), (5, "striped turquoise"), (5, "pale black")),
new Bag("wavy crimson", (5, "pale yellow")),
new Bag("dim purple", (4, "bright cyan"), (5, "dark tan"), (1, "posh silver"), (2, "pale maroon")),
new Bag("mirrored cyan", (5, "mirrored aqua"), (4, "dim tomato"), (1, "wavy gold")),
new Bag("wavy turquoise", (4, "pale orange")),
new Bag("pale crimson", (5, "light crimson")),
new Bag("drab olive", (5, "shiny silver"), (5, "shiny white"), (1, "dark olive")),
new Bag("light violet", (5, "posh lime"), (4, "dull salmon")),
new Bag("clear gold", (2, "dark gray")),
new Bag("dark blue", (1, "faded plum"), (4, "faded fuchsia"), (5, "clear red"), (1, "dull orange")),
new Bag("dim orange", (3, "light blue"), (1, "faded orange"), (1, "dim fuchsia"), (5, "drab yellow")),
new Bag("mirrored tan", (3, "mirrored gold")),
new Bag("posh purple", (2, "posh silver"), (1, "dark brown"), (3, "dotted olive"), (4, "shiny white")),
new Bag("shiny coral", (4, "bright indigo"), (5, "plaid teal")),
new Bag("faded fuchsia", (4, "shiny maroon"), (4, "clear bronze")),
new Bag("plaid brown", (2, "posh tan"), (2, "faded olive"), (3, "dull tomato"), (4, "dark plum")),
new Bag("faded coral", (3, "light yellow"), (1, "pale red"), (5, "bright cyan"), (2, "dark coral")),
new Bag("drab gray", (5, "light tan"), (3, "vibrant violet")),
new Bag("striped indigo", (5, "vibrant tomato"), (2, "dull orange"), (5, "bright maroon")),
new Bag("dull red", (1, "dark lime"), (1, "mirrored maroon"), (3, "vibrant white")),
new Bag("plaid indigo", (1, "mirrored coral"), (4, "dotted red"), (2, "wavy chartreuse")),
new Bag("faded lime", (1, "faded yellow"), (5, "faded gold"), (4, "faded aqua"), (1, "wavy tomato")),
new Bag("clear tan", (3, "posh silver"), (5, "dull plum")),
new Bag("clear lime", (5, "dull lavender"), (3, "faded magenta"), (2, "shiny olive"), (1, "posh orange")),
new Bag("dotted teal", (3, "drab yellow")),
new Bag("wavy violet", (5, "dotted beige")),
new Bag("faded bronze", (2, "pale maroon"), (4, "pale silver"), (4, "mirrored fuchsia")),
new Bag("striped black", (4, "dim silver")),
new Bag("wavy orange", (5, "muted coral")),
new Bag("plaid violet", (4, "posh turquoise")),
new Bag("muted violet", (3, "plaid beige")),
new Bag("striped plum", (4, "dark silver"), (5, "bright brown")),
new Bag("bright silver", (1, "muted purple")),
new Bag("dim chartreuse", (4, "wavy plum"), (5, "muted maroon")),
new Bag("faded orange", (2, "pale maroon"), (4, "pale gray"), (4, "pale yellow"), (4, "faded tomato")),
new Bag("dotted black", (1, "vibrant aqua"), (3, "posh black"), (2, "dim lavender"), (3, "pale coral")),
new Bag("vibrant gold", (4, "dull chartreuse"), (3, "muted green"), (1, "shiny turquoise")),
new Bag("dull bronze", (1, "dim salmon"), (4, "striped crimson")),
new Bag("clear blue", (2, "clear coral"), (5, "vibrant chartreuse")),
new Bag("shiny tan", (1, "shiny gold")),
new Bag("dotted brown", (5, "dotted red"), (4, "shiny gray"), (3, "vibrant gray")),
new Bag("posh maroon", (5, "dull coral")),
new Bag("drab tomato", (4, "dull silver")),
new Bag("muted white", (4, "shiny olive"), (1, "dull tan")),
new Bag("wavy teal", (2, "wavy plum"), (5, "posh chartreuse")),
new Bag("shiny gray", (5, "dull salmon"), (1, "dull crimson")),
new Bag("dim silver", (2, "pale maroon"), (3, "plaid olive")),
new Bag("wavy magenta", (4, "vibrant silver")),
new Bag("drab magenta", (4, "muted olive"), (5, "dark chartreuse"), (4, "mirrored tomato"), (2, "bright magenta")),
new Bag("muted coral", (3, "pale beige")),
new Bag("vibrant tomato", (1, "vibrant plum"), (4, "bright black"), (2, "bright crimson"), (5, "faded turquoise")),
new Bag("vibrant white", (5, "plaid blue"), (4, "dull cyan"), (1, "dull fuchsia")),
new Bag("bright brown", (2, "shiny tan")),
new Bag("clear beige", (3, "light lime"), (1, "faded turquoise"), (4, "mirrored salmon")),
new Bag("dull plum", (4, "drab yellow")),
new Bag("light green", (5, "vibrant yellow"), (1, "drab green")),
new Bag("wavy silver"),
new Bag("vibrant coral", (3, "faded bronze")),
new Bag("light plum", (2, "pale salmon"), (5, "dull teal"), (1, "dark plum")),
new Bag("pale orange"),
new Bag("dull gray", (1, "vibrant crimson")),
new Bag("dull coral", (4, "shiny white"), (3, "wavy white"), (1, "pale green")),
new Bag("muted bronze", (3, "drab yellow"), (1, "dotted teal"), (1, "clear gold")),
new Bag("vibrant indigo", (3, "dim violet"), (3, "pale yellow"), (1, "pale indigo"), (5, "shiny gold")),
new Bag("dark indigo", (4, "light beige")),
new Bag("faded brown", (2, "dim fuchsia"), (5, "dull turquoise"), (1, "plaid salmon"), (5, "light brown")),
new Bag("striped salmon", (1, "muted olive"), (2, "dull purple"), (1, "dim tomato")),
new Bag("muted maroon", (4, "plaid tan"), (5, "light gray"), (4, "pale turquoise"), (3, "faded maroon")),
new Bag("drab silver", (1, "bright chartreuse"), (3, "plaid coral")),
new Bag("dim green", (1, "plaid olive"), (1, "dim tomato"), (3, "muted aqua"), (2, "light gold")),
new Bag("light salmon", (4, "muted orange")),
new Bag("bright teal", (5, "striped gold")),
new Bag("dull teal"),
new Bag("bright maroon", (5, "pale green"), (3, "pale brown"), (2, "posh purple"), (3, "light gold")),
new Bag("pale lavender", (5, "dim beige"), (5, "shiny tan"), (4, "muted blue")),
new Bag("light turquoise", (5, "mirrored olive"), (4, "striped maroon")),
new Bag("shiny beige", (5, "dim bronze"), (2, "light gold"), (4, "drab beige")),
new Bag("clear olive", (1, "mirrored olive"), (2, "muted orange"), (3, "faded salmon"), (1, "bright red")),
new Bag("shiny magenta", (3, "wavy beige"), (1, "bright red")),
new Bag("pale indigo", (1, "striped beige"), (4, "muted aqua"), (3, "muted olive"), (1, "dull teal")),
new Bag("vibrant fuchsia", (5, "striped lavender"), (2, "dull orange"), (4, "striped beige"), (1, "posh silver")),
new Bag("wavy plum", (5, "dull orange")),
new Bag("striped bronze", (4, "bright lavender"), (2, "pale gray"), (1, "dull orange")),
new Bag("shiny aqua", (4, "muted tan")),
new Bag("drab cyan", (4, "clear plum")),
new Bag("drab turquoise", (3, "dull tan")),
new Bag("striped coral", (3, "striped brown"), (5, "bright yellow")),
new Bag("wavy coral", (4, "dull teal"), (3, "vibrant fuchsia"), (2, "vibrant teal")),
new Bag("drab chartreuse", (3, "drab blue"), (5, "vibrant fuchsia")),
new Bag("plaid red", (2, "posh purple"), (5, "dull salmon"), (4, "vibrant fuchsia")),
new Bag("striped turquoise", (4, "dotted beige"), (4, "vibrant crimson")),
new Bag("dark aqua", (4, "dotted olive"), (1, "wavy orange"), (5, "dotted violet")),
new Bag("posh violet", (1, "muted magenta"), (5, "mirrored magenta"), (4, "light chartreuse")),
new Bag("drab coral", (2, "bright olive"), (2, "wavy tan"), (1, "dark aqua"), (5, "mirrored teal")),
new Bag("bright purple", (3, "shiny teal"), (4, "faded tomato"), (3, "wavy plum"), (1, "wavy red")),
new Bag("dotted maroon", (5, "mirrored teal"), (5, "dull gray"), (3, "vibrant yellow")),
new Bag("dotted crimson", (1, "dim salmon"), (4, "clear gray"), (4, "wavy red")),
new Bag("plaid white", (5, "pale salmon"), (5, "vibrant teal"), (2, "shiny coral")),
new Bag("dotted lime", (4, "dark yellow"), (1, "dull lime")),
new Bag("shiny red", (1, "bright brown"), (2, "plaid yellow")),
new Bag("clear purple", (4, "mirrored olive"), (5, "light olive"), (2, "dark gold"), (4, "bright turquoise")),
new Bag("mirrored maroon", (4, "muted aqua"), (1, "bright lavender"), (2, "bright cyan"), (5, "dull orange")),
new Bag("bright lavender", (3, "pale brown"), (1, "striped gold"), (4, "pale chartreuse"), (3, "bright olive")),
new Bag("drab maroon", (1, "pale orange")),
new Bag("muted crimson", (4, "light gray"), (2, "muted white")),
new Bag("dark beige", (1, "pale chartreuse"), (5, "pale gray"), (4, "shiny indigo")),
new Bag("clear silver", (5, "mirrored gold"), (2, "muted brown")),
new Bag("dim turquoise", (5, "faded orange"), (4, "dotted yellow")),
new Bag("dotted beige", (1, "plaid teal")),
new Bag("dotted fuchsia", (5, "posh tomato"), (4, "vibrant violet")),
new Bag("faded white", (1, "wavy beige"), (3, "wavy white"), (5, "clear indigo")),
new Bag("plaid salmon", (4, "light cyan"), (5, "drab lime"), (5, "muted green"), (5, "dim lavender")),
new Bag("striped lavender", (5, "pale yellow"), (1, "dotted red"), (1, "plaid blue")),
new Bag("muted olive", (2, "dark plum")),
new Bag("drab indigo", (3, "vibrant chartreuse"), (3, "plaid teal"), (1, "dotted maroon"), (5, "dull lime")),
new Bag("bright gray", (4, "faded indigo"), (1, "drab white"), (3, "muted blue")),
new Bag("dotted silver", (2, "light green"), (3, "wavy coral"), (1, "bright chartreuse"), (5, "wavy violet")),
new Bag("vibrant magenta", (4, "light indigo"), (1, "light lime"), (3, "shiny coral")),
new Bag("pale yellow", (5, "muted aqua"), (5, "dark plum"), (3, "dark brown")),
new Bag("drab fuchsia", (5, "faded cyan")),
new Bag("plaid orange", (2, "dim silver")),
new Bag("plaid lavender", (1, "pale maroon"), (2, "mirrored fuchsia"), (4, "striped yellow"), (5, "light lavender")),
new Bag("pale violet", (3, "clear chartreuse"), (4, "posh black"), (2, "bright teal"), (4, "faded turquoise")),
new Bag("light white", (3, "dotted indigo"), (3, "dull yellow"), (3, "plaid brown"), (2, "muted gold")),
new Bag("wavy cyan", (2, "pale aqua"), (4, "dim cyan"), (1, "vibrant chartreuse")),
new Bag("posh orange", (1, "pale beige"), (2, "dull coral"), (4, "pale chartreuse")),
new Bag("clear plum", (1, "bright red"), (2, "dull tomato"), (5, "striped silver")),
new Bag("drab tan", (4, "muted olive")),
new Bag("striped tomato", (3, "posh orange")),
new Bag("muted beige", (5, "mirrored violet"), (1, "dull orange")),
new Bag("mirrored purple", (4, "muted olive"), (5, "dull lime")),
new Bag("light teal", (5, "pale gray"), (5, "plaid lavender"), (2, "light plum")),
new Bag("dim teal", (2, "striped beige"), (5, "pale aqua"), (4, "pale yellow")),
new Bag("dotted chartreuse", (3, "vibrant lavender")),
new Bag("dim tomato", (3, "bright cyan"), (3, "muted olive"), (4, "clear teal"), (1, "pale chartreuse")),
new Bag("vibrant teal", (2, "bright red"), (4, "wavy chartreuse"), (2, "posh silver"), (4, "bright olive")),
new Bag("mirrored plum", (2, "striped yellow"), (2, "striped lavender"), (4, "dark black")),
new Bag("plaid gray", (2, "plaid teal")),
new Bag("vibrant gray", (1, "dim brown")),
new Bag("drab salmon", (5, "dotted red"), (4, "light gold"), (3, "mirrored maroon"), (1, "dotted plum")),
new Bag("dull lime", (3, "shiny turquoise")),
new Bag("clear green", (4, "plaid maroon"), (1, "dim crimson"), (5, "striped white")),
new Bag("dotted red", (1, "dull teal")),
new Bag("faded purple", (3, "shiny salmon"), (3, "clear tan"), (3, "bright magenta")),
new Bag("dark magenta", (1, "dark tan")),
new Bag("mirrored red", (1, "drab magenta"), (3, "wavy bronze"), (5, "shiny chartreuse")),
new Bag("dim blue", (2, "light plum"), (1, "faded crimson")),
new Bag("dark cyan", (1, "dull plum"), (5, "dim purple")),
new Bag("drab lavender", (3, "dim purple"), (2, "dotted red")),
new Bag("posh red", (1, "plaid lavender"), (5, "vibrant white"), (1, "bright magenta")),
new Bag("pale cyan", (2, "striped yellow"), (3, "dotted red"), (5, "dull plum"), (2, "plaid blue")),
new Bag("pale black", (1, "wavy beige"), (1, "clear magenta"), (4, "wavy red")),
new Bag("dotted aqua", (5, "vibrant lavender"), (3, "muted brown")),
new Bag("clear brown", (5, "posh brown")),
new Bag("light coral", (4, "dull turquoise"), (1, "mirrored gold"), (5, "mirrored olive"), (1, "dull gray")),
new Bag("dotted bronze", (4, "striped brown"), (3, "posh teal")),
new Bag("faded aqua", (1, "dull yellow"), (2, "dark bronze")),
new Bag("dim magenta", (2, "drab red"), (3, "clear tan"), (1, "faded lime")),
new Bag("clear fuchsia", (5, "clear red"), (3, "plaid crimson"), (4, "bright magenta"), (3, "faded tan")),
new Bag("faded blue", (2, "clear chartreuse"), (1, "vibrant crimson"), (3, "faded tomato")),
new Bag("dark tomato", (5, "posh brown"), (5, "bright olive"), (2, "dull silver")),
new Bag("bright orange", (3, "dotted teal"), (5, "posh orange"), (5, "wavy blue")),
new Bag("dim cyan", (5, "dotted red"), (2, "wavy gold"), (2, "dull lime"), (4, "bright olive")),
new Bag("pale olive", (2, "dull lime"), (4, "wavy white"), (4, "pale aqua")),
new Bag("dim lavender", (5, "shiny green"), (3, "shiny cyan")),
new Bag("vibrant brown", (2, "light magenta"), (5, "vibrant violet"), (3, "drab white")),
new Bag("striped teal", (3, "clear salmon")),
new Bag("pale salmon", (5, "dull purple"), (1, "dark gray"), (2, "dim violet"), (4, "shiny white")),
new Bag("wavy olive", (4, "vibrant fuchsia"), (2, "shiny olive")),
new Bag("drab aqua", (2, "shiny maroon"), (1, "pale orange"), (5, "wavy orange")),
new Bag("mirrored bronze", (3, "dim blue"), (4, "drab chartreuse")),
new Bag("clear orange", (4, "mirrored cyan"), (1, "striped red")),
new Bag("shiny fuchsia", (4, "plaid teal"), (3, "vibrant coral"), (5, "shiny silver"), (3, "dotted red")),
new Bag("vibrant black", (5, "light coral"), (3, "bright lavender"), (1, "dull violet")),
new Bag("dim yellow", (4, "dark plum"), (4, "shiny coral")),
new Bag("shiny lavender", (3, "dull tomato"), (1, "dark cyan"), (4, "light brown")),
new Bag("dull maroon", (3, "light purple"), (4, "striped blue")),
new Bag("pale beige", (5, "wavy chartreuse"), (5, "dull purple"), (3, "pale orange"), (3, "dotted teal")),
new Bag("vibrant plum", (3, "dull turquoise"), (3, "shiny gold"), (5, "dark black")),
new Bag("clear tomato", (3, "mirrored lime"), (4, "shiny red")),
new Bag("drab crimson", (1, "clear silver"), (3, "wavy chartreuse"), (3, "pale bronze"), (2, "bright cyan")),
new Bag("posh bronze", (2, "faded indigo"), (1, "clear red")),
new Bag("drab purple", (1, "pale coral"), (3, "faded bronze"), (2, "striped yellow"), (4, "light orange")),
new Bag("muted tomato", (4, "pale chartreuse")),
new Bag("dim fuchsia", (5, "shiny white")),
new Bag("dotted turquoise", (3, "drab plum"), (3, "pale olive"), (4, "posh silver")),
new Bag("posh chartreuse", (4, "dotted indigo")),
new Bag("dim olive", (3, "posh silver"), (5, "dotted beige"), (5, "light lime")),
new Bag("wavy gold", (5, "muted aqua"), (4, "muted coral")),
new Bag("striped purple", (1, "pale violet"), (1, "faded beige"), (5, "pale gray"), (4, "muted yellow")),
new Bag("faded cyan", (4, "pale lime"), (2, "muted brown")),
new Bag("shiny plum", (1, "muted purple")),
new Bag("faded crimson", (4, "striped white")),
new Bag("wavy green", (5, "dotted salmon"), (3, "dim fuchsia"), (3, "wavy aqua")),
new Bag("mirrored magenta", (3, "drab black"), (2, "posh turquoise"), (5, "bright indigo")),
new Bag("dull green", (3, "dull lime"), (2, "bright silver")),
new Bag("pale turquoise", (5, "muted orange"), (3, "plaid bronze"), (5, "bright teal")),
new Bag("striped blue", (4, "light lavender"), (4, "light orange"), (4, "muted coral"), (5, "wavy olive")),
new Bag("plaid fuchsia", (3, "striped turquoise"), (1, "shiny bronze")),
new Bag("posh plum", (4, "wavy silver"), (4, "vibrant crimson"), (5, "muted cyan")),
new Bag("faded tomato", (5, "mirrored coral")),
new Bag("vibrant cyan", (4, "muted green")),
new Bag("vibrant lavender", (1, "dull tan")),
new Bag("faded teal", (4, "dim red"), (1, "posh red")),
new Bag("plaid turquoise", (3, "vibrant crimson"), (4, "striped yellow")),
new Bag("posh gold", (3, "dull silver"), (2, "dark black"), (3, "faded lavender")),
new Bag("light blue", (4, "shiny gold"), (5, "dotted beige"), (1, "dim brown"), (2, "shiny fuchsia")),
new Bag("mirrored chartreuse", (4, "shiny tan"), (2, "dim purple"), (2, "pale cyan")),
new Bag("light cyan", (2, "dotted olive"), (2, "dull crimson"), (4, "pale turquoise")),
new Bag("wavy yellow", (5, "vibrant fuchsia"), (3, "drab fuchsia")),
new Bag("drab teal", (2, "mirrored green")),
new Bag("bright red", (1, "pale beige")),


        };

    }
}